version: '3.8'

services:
  app:
    container_name: sellect-app
    image: sellect-app:latest  # 미리 빌드된 이미지를 사용
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    ports:
      - "9090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker 소켓 마운트

