spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      protocol: ${REDIS_PROTOCOL:redis://} # 기본값 추가
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false} # 기본값 추가
      timeout: 10000  # 연결 타임아웃 10초
      lettuce:
        pool:
          max-active: 10  # 최대 활성 연결
          max-idle: 5     # 최대 유휴 연결
          min-idle: 2     # 최소 유휴 연결
          time-between-eviction-runs: 30000  # 유휴 연결 정리 주기 (ms)
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL} # 기본값 없음
      sasl.mechanism: ${KAFKA_SASL_MECHANISM} # 기본값 없음
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG} # 기본값 없음
      sasl.client.callback.handler.class: ${KAFKA_SASL_CLIENT_CALLBACK_HANDLER} # 기본값 없음

server:
  host: ${HOST_URL}
  tomcat:
    accept-count: 10000

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

kakao:
  pay:
    secret-key: ${KAKAO_PAY_SECRET_KEY}

storage:
  file-system:
    location: /tmp/spring-boot-upload
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION}
  tus:
    storage-path: /tmp/tus-upload
    upload-uri: /api/v1/images/upload
    upload-expiration: 86400
cloudfront:
  domain-name: ${CLOUDFRONT_DOMAIN_NAME:0.0.0.0}

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8080

logging:
  level:
    com.sellect.server.search.batch: DEBUG
    com.sellect.server.payment.application: DEBUG  # PaymentService 로그
    org.springframework.kafka: DEBUG  # Kafka 소비 로그
    org.springframework.data.redis: INFO  # Redis 동작 로그
    org.springframework.jdbc: DEBUG  # DB 쿼리 로그
