spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true  # 기존 DB가 있을 경우 필요한 설정
    locations: classpath:db/migration  # 마이그레이션 SQL 파일 위치

jwt:
  secret: ${JWT_SECRET}  # JWT 시크릿 키 설정
  expiration: ${JWT_EXPIRATION}

kakao:
  pay:
    secret-key: ${KAKAO_PAY_SECRET_KEY}
storage:
  file-system:
    location: /tmp/spring-boot-upload
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION}

